package net.justmachinery.futility.generator

import org.intellij.lang.annotations.Language
import java.io.File


fun main(args : Array<String>) {
    val root = File(args.single())
    root.deleteRecursively()
    val outputDir = root.resolve("net/justmachinery/futility/primitives")
    outputDir.mkdirs()
    for(primitive in primitives) {
        outputDir.resolve("${primitive.wrap}Operators.kt").writeText(primitive.operatorsFile())
    }
}

/**
 * How many numbered relation slots to generate operators for. Must match the AdditiveWithN/MultipliesToN/
 * DividesToN interfaces declared in Wrappers.kt. Note that if you need more than four you can actually just
 * define them yourself. It's all extension functions...
 */
private const val OPERATION_INTERFACE_COUNT = 4

private class Primitive(val type : String) {
    val wrap = "${type}Wrapper"
    val integer = type == "Int" || type == "Long"

    val sumOfRaw = if(type == "Float") {
        "sumByFloat { it.raw }"
    } else {
        "sumOf { it.raw }"
    }
}

private val primitives = listOf(Primitive("Int"), Primitive("Long"), Primitive("Float"), Primitive("Double"))

private fun emitIf(condition : Boolean, cb : ()->String) = if(condition) "\n" + cb().trimIndent() else ""

@Language("kotlin")
private fun Primitive.operatorsFile() = """
//Source code generated by WrappersGenerator.kt, do not edit
@file:Suppress("unused")
package net.justmachinery.futility.primitives

import kotlin.math.abs
import net.justmachinery.futility.atLeast
import net.justmachinery.futility.atMost
import net.justmachinery.futility.clamp
import net.justmachinery.futility.isWithin
import net.justmachinery.futility.squared
${emitIf(integer) { """
import kotlin.math.ceil
import kotlin.math.floor
import net.justmachinery.futility.ceilDiv
""" }}
${emitIf(type == "Long") { """
import net.justmachinery.futility.clampToInt
""" }}
${emitIf(type == "Float") { """
import net.justmachinery.futility.collections.sumByFloat
""" }}

//Scaling by raw numbers
public operator fun <Unit : RawScalable> $wrap<Unit>.times(scale : $type) : $wrap<Unit> = $wrap(raw * scale)
public operator fun <Unit : RawScalable> $wrap<Unit>.div(divisor : $type) : $wrap<Unit> = $wrap(raw / divisor)
${emitIf(type != "Int") { """
public operator fun <Unit : RawScalable> $wrap<Unit>.times(scale : Int) : $wrap<Unit> = $wrap(raw * scale)
public operator fun <Unit : RawScalable> $wrap<Unit>.div(divisor : Int) : $wrap<Unit> = $wrap(raw / divisor)
""" }}
${emitIf(integer) { """
public operator fun <Unit : RawScalable> $wrap<Unit>.rem(divisor : $type) : $wrap<Unit> = $wrap(raw % divisor)
public fun <Unit : RawScalable> $wrap<Unit>.ceilDiv(divisor : $type) : $wrap<Unit> = $wrap(raw.ceilDiv(divisor))
@Deprecated("Use ceilDiv", ReplaceWith("this.ceilDiv(divisor)"))
public fun <Unit : RawScalable> $wrap<Unit>.divRoundUp(divisor : $type) : $wrap<Unit> = ceilDiv(divisor)
public fun <Unit : RawScalable> $wrap<Unit>.timesUp(scale : Double) : $wrap<Unit> = $wrap(ceil(raw * scale).to$type())
public fun <Unit : RawScalable> $wrap<Unit>.timesDown(scale : Double) : $wrap<Unit> = $wrap(floor(raw * scale).to$type())
""" }}
${emitIf(type == "Long") { """
public fun <Unit> LongWrapper<Unit>.clampToInt() : IntWrapper<Unit> = IntWrapper(raw.clampToInt())
""" }}

//Ordering. These mirror the equivalents in Numbers.kt.
public operator fun <Unit : Ordered> $wrap<Unit>.compareTo(other : $wrap<Unit>) : Int = raw.compareTo(other.raw)
public fun <Unit : Ordered> $wrap<Unit>.atMost(other : $wrap<Unit>) : $wrap<Unit> = $wrap(raw.atMost(other.raw))
public fun <Unit : Ordered> $wrap<Unit>.atLeast(other : $wrap<Unit>) : $wrap<Unit> = $wrap(raw.atLeast(other.raw))
public fun <Unit : Ordered> $wrap<Unit>.clamp(minimumValue : $wrap<Unit>, maximumValue : $wrap<Unit>) : $wrap<Unit> = $wrap(raw.clamp(minimumValue.raw, maximumValue.raw))
public fun <Unit : Ordered> $wrap<Unit>.isWithin(other : $wrap<Unit>, tolerance : $wrap<Unit>) : Boolean = raw.isWithin(other.raw, tolerance.raw)
public fun <Unit : Ordered> Iterable<$wrap<Unit>>.minOrNull() : $wrap<Unit>? = minByOrNull { it.raw }
public fun <Unit : Ordered> Iterable<$wrap<Unit>>.maxOrNull() : $wrap<Unit>? = maxByOrNull { it.raw }
${(1..OPERATION_INTERFACE_COUNT).joinToString("") { """
//Relational operators
@JvmName("plus$it")
public operator fun <Unit : AdditiveWith$it<OtherUnit>, OtherUnit> ${wrap}<Unit>.plus(other : ${wrap}<OtherUnit>) : ${wrap}<Unit> = ${wrap}(raw + other.raw)
@JvmName("minus$it")
public operator fun <Unit : AdditiveWith$it<OtherUnit>, OtherUnit> ${wrap}<Unit>.minus(other : ${wrap}<OtherUnit>) : ${wrap}<Unit> = ${wrap}(raw - other.raw)
@JvmName("unaryMinus$it")
public operator fun <Unit : AdditiveWith$it<Unit>> ${wrap}<Unit>.unaryMinus() : ${wrap}<Unit> = ${wrap}(-raw)
@JvmName("abs$it")
public fun <Unit : AdditiveWith$it<Unit>> ${wrap}<Unit>.abs() : ${wrap}<Unit> = ${wrap}(abs(raw))
@JvmName("sum$it")
public fun <Unit : AdditiveWith$it<Unit>> Iterable<${wrap}<Unit>>.sum() : ${wrap}<Unit> = ${wrap}(${sumOfRaw})
@JvmName("times$it")
public operator fun <Unit : MultipliesTo$it<OtherUnit, ResultUnit>, OtherUnit, ResultUnit> ${wrap}<Unit>.times(other : ${wrap}<OtherUnit>) : ${wrap}<ResultUnit> = ${wrap}(raw * other.raw)
@JvmName("squared$it")
public fun <Unit : MultipliesTo$it<Unit, ResultUnit>, ResultUnit> ${wrap}<Unit>.squared() : ${wrap}<ResultUnit> = ${wrap}(raw.squared())
@JvmName("div$it")
public operator fun <Unit : DividesTo$it<OtherUnit, ResultUnit>, OtherUnit, ResultUnit> ${wrap}<Unit>.div(other : ${wrap}<OtherUnit>) : ${wrap}<ResultUnit> = ${wrap}(raw / other.raw)
@JvmName("divRaw$it")
public operator fun <Unit : RawDividesTo$it<OtherUnit>, OtherUnit> ${wrap}<Unit>.div(other : ${wrap}<OtherUnit>) : $type = raw / other.raw
${emitIf(!integer) { """
@JvmName("lerp$it")
public fun <Unit> lerp(from : ${wrap}<Unit>, to : ${wrap}<Unit>, fraction : ${type}) : ${wrap}<Unit>
where Unit : AdditiveWith$it<Unit>, Unit : RawScalable = from + (to - from) * fraction
""" }}
""" }}
""".trimIndent()

